{
 "title": "CP4D workload",
 "description": "CP4D user workload monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Memory usage by projects",
   "type": "bargauge",
   "description": "Overall memory usage by all the projects and environments\n",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "project_total_memory_limits_total",
     "legendFormat": "Total memory limits"
    },
    {
     "expr": "project_total_memory_requests_total",
     "legendFormat": "Total memory requested"
    },
    {
     "expr": "project_total_memory_usage_total",
     "legendFormat": "Total memory usage"
    }
   ]
  },
  {
   "title": "CPU consumption",
   "type": "bargauge",
   "description": "Overall project CPU consumption by all environments",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "project_total_cpu_limits_total", "legendFormat": "Total CPU limits" },
    {
     "expr": "project_total_CPU_requests_total",
     "legendFormat": "Total CPU requests"
    },
    { "expr": "project_total_cpu_usage_total", "legendFormat": "Total CPU usage" }
   ]
  },
  {
   "title": "CP4D jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "active_jobs_count_total", "legendFormat": "Active jobs" },
    { "expr": "jobs_count_total", "legendFormat": "Overall amount of jobs" }
   ]
  }
 ]
}