{
 "title": "OpenShift Capacity",
 "description": "Max values of MEM and CPU usage in the last 24 hours",
 "tags": [
  "OpenShift",
  "Capacity"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Worker Nodes CPU stats",
   "type": "bargauge",
   "description": "Cores Installed: Number of CPUs s on all the worker  nodes\n\nCores Used: Number of CPUs used by OpenShift pods  on all the worker  nodes\n\nCores Requests: Number of CPUs requested by OpenShift pods  on all the worker  nodes\n\nCores Limits : Maximum  number of CPUs  that can be used by OpenShift pods  on all the worker  nodes\n\n\nWhen you specify the resource request for Containers in a Pod, the scheduler uses this information to decide which node to place the Pod on. \n\nWhen you specify a resource limit for a Container, OpenShift enforces those limits so that the running container is not allowed to use more of that resource than the limit you set.  ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{node=~\".+node.+\"})",
     "legendFormat": "Cores Installed"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{node=~\".+node.+\"})",
     "legendFormat": "Cores Used"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{node=~\".+node.+\"})",
     "legendFormat": "Cores Requests"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits_cpu_cores{node=~\".+node.+\"})",
     "legendFormat": "Cores Limits"
    }
   ]
  },
  {
   "title": "Worker Nodes CPU Usage",
   "type": "bargauge",
   "description": "CPU usage in % on worker nodes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(\n  instance:node_cpu_utilisation:rate1m{job=\"node-exporter\",instance=~\".+ocnode.+\"}\n*\n  instance:node_num_cpu:sum{job=\"node-exporter\",instance=~\".+ocnode.+\"}\n)\n/ scalar(sum(instance:node_num_cpu:sum{job=\"node-exporter\",instance=~\".+ocnode.+\"}))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Worker Nodes Memory stats",
   "type": "bargauge",
   "description": "Memory Installed: Amount of RAM on all the worker  nodes\n\nMemory Usage: RAM used by OpenShift pods  on all the worker  nodes\n\nMemory Requests: RAM requested by OpenShift pods  on all the worker  nodes\n\nMemory Limits : Maximum allowed  RAM  that can be used by OpenShift pods  on all the worker  nodes\n\n\nWhen you specify the resource request for Containers in a Pod, the scheduler uses this information to decide which node to place the Pod on. \n\nWhen you specify a resource limit for a Container, OpenShift enforces those limits so that the running container is not allowed to use more of that resource than the limit you set.  ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{node=~\".+node.+\"})",
     "legendFormat": "Memory Installed"
    },
    {
     "expr": "sum(container_memory_rss{node=~\".+node.+\",container!=\"\"})",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\".+node.+\"})",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\".+node.+\"})",
     "legendFormat": "Memory Limits"
    }
   ]
  },
  {
   "title": "Worker Nodes Memory Available",
   "type": "bargauge",
   "description": "Free RAM in GB on the worker nodes. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\".+node.+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CP4D tenant CPU stats",
   "type": "bargauge",
   "description": "\nCores Used: Number of CPUs used by CloudpackForData  pods  on all the worker  nodes\n\nCores Requests: Number of CPUs requested by CloudpackForData pods  on all the worker  nodes\n\nCores Limits : Maximum  number of CPUs  that can be used by CloudpackForData pods  on all the worker  nodes\n\n\nWhen you specify the resource request for Containers in a Pod, the scheduler uses this information to decide which node to place the Pod on. \n\nWhen you specify a resource limit for a Container, OpenShift enforces those limits so that the running container is not allowed to use more of that resource than the limit you set.  ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"cpd\"})",
     "legendFormat": "Cores Used"
    },
    {
     "expr": "namespace:kube_pod_container_resource_requests_cpu_cores:sum{namespace=\"cpd\"}",
     "legendFormat": "Cores Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"cpd\"})",
     "legendFormat": "Cores Limits"
    },
    {}
   ]
  },
  {
   "title": "CP4D tenant Memory stats",
   "type": "bargauge",
   "description": "\nMemory Used: RAM used by CloudpackForData  pods  on all the worker  nodes\n\nMemory Requests: RAM requested by CloudpackForData pods  on all the worker  nodes\n\nMemory Limits : Maximum  number of RAM that can be used by CloudpackForData pods  on all the worker  nodes\n\n\nWhen you specify the resource request for Containers in a Pod, the scheduler uses this information to decide which node to place the Pod on. \n\nWhen you specify a resource limit for a Container, OpenShift enforces those limits so that the running container is not allowed to use more of that resource than the limit you set.  ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=\"cpd\", container!=\"\"})",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"cpd\"})",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"cpd\"})",
     "legendFormat": "Memory Limits"
    }
   ]
  }
 ]
}